# Generated by Django 3.2.6 on 2021-08-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duser', models.CharField(max_length=100)),
                ('dpass', models.CharField(max_length=100)),
            ],
        ),
    ]
