# Generated by Django 3.2.6 on 2021-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gaurds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guser', models.CharField(max_length=100)),
                ('gname', models.CharField(max_length=100)),
                ('gpass', models.CharField(max_length=100)),
            ],
        ),
    ]
