# Generated by Django 3.2.6 on 2021-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaurd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('guest_num', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('intime', models.CharField(max_length=100)),
                ('exittime', models.CharField(max_length=100)),
            ],
        ),
    ]
